Barang/urls.py
from django.urls import path, include
from . import views

app_name = 'barang'
urlpatterns = [
    path('barang/', views.createBarang , name ='createbarang'),
    path('', views.homepage , name = 'homepage'),
]

TP_PPW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path("", include('Barang.urls')),
    path("review/", include('homepage.urls')), 
    path('subscriber/',include('subscriber.urls')),
    path('deskripsi/', include('deskripsi.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT )
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

deskripsi/urls.py
from django.urls import path, include
from deskripsi.views import detail_barang,beli_barang,barang_terbeli

urlpatterns = [
    path("konfirmasi/<slug_barang>/" , beli_barang , name= 'barangbeli'),
    path('semuabarangdibeli/' , barang_terbeli , name='barangterbeli'),
    path("<slug_barang>/" , detail_barang , name= 'barangdetail'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.review_create, name='review_create'),
]

subscriber/urls.py
from django.urls import path
from . import views

app_name = 'subscriber'
urlpatterns = [
    path('subscriber_create/',views.subscriber_create,name='subscriber_create'),
    path('subscriber/',views.subscriber,name='subscriber'),
]

Barang/models.py
from django.db import models
from django.template.defaultfilters import slugify

class BarangModel(models.Model):
   Choice = {
       ("SkinCare", "Skincare"),
       ("Bedak", "Bedak"),
       ("Pelembab", "Pelembab"),
       ("Lipstik", "Lipstik"),
   }
   Choice_gender = {
       ("Perempuan", "Perempuan"),
       ("Laki-Laki", "Laki-Laki"),
       ("Both", "Both"),
   }
   brand_barang = models.CharField(max_length=250)
   nama_barang = models.CharField(max_length=500)
   harga = models.IntegerField(default=0)
   kategori_barang = models.CharField(choices=Choice, max_length=100)
   ukuran_barang = models.CharField(max_length=50)
   terbeli = models.BooleanField(default=False)
   gender = models.CharField( max_length=50 , choices = Choice_gender)
   picture = models.ImageField(upload_to = "media")
   slug = models.SlugField(unique=True)


   def _get_unique_slug(self): #For generating slug (url parameter for vendor)
      slug = slugify(self.nama_barang)
      unique_slug = slug
      num = 1
      while BarangModel.objects.filter(slug=unique_slug).exists():
         unique_slug = '{}-{}'.format(slug, num)
         num += 1
      return unique_slug

   def save(self, *args, **kwargs):
      if not self.slug:
         self.slug = self._get_unique_slug()
      super().save(*args,**kwargs)

deskripsi/models.py
from django.db import models
from Barang.models import BarangModel


# Create your models here.
class BarangPembeli(models.Model):
    barang = models.ForeignKey(BarangModel,on_delete=models.CASCADE)
    def __str__(self):
        return self.barang
        

homepage/models.py
from django.db import models


class Review(models.Model):

    fill = models.CharField(max_length=200)
    name = models.CharField(max_length=22, default='anonimous')

    def __str__(self):
        return "{}. {}".format(self.id, self.name)

subscriber/models.py
from django.db import models

from django.db import models



class Subscriber(models.Model):

    name = models.CharField(max_length = 30)
    email = models.EmailField(max_length = 30)

Barang/forms.py
from django import forms
from Barang.models import BarangModel
from django.utils.text import slugify

class BarangForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["kategori_barang"].widget.attrs.update({'class': 'form-control form-group row'})
        self.fields["gender"].widget.attrs.update({'class': 'form-control form-group row'})

    class Meta:
        model = BarangModel
        exclude = ('slug', 'base64_pic', 'terbeli')

        widgets= {
            'brand_barang': forms.TextInput(attrs={'class' : 'form-control form-group row' , 'placeholder' : 'Brand'}),
            'nama_barang' : forms.TextInput(attrs={'class': 'form-control form-group row', 'placeholder' : 'Name'}),
            'harga' : forms.NumberInput(attrs={'class': 'form-control form-group row' , 'placeholder' : 'Harga'}),
            'ukuran_barang' : forms.TextInput(attrs={'class': 'form-control form-group row' , 'placeholder' : 'Size'}),
            'deskripsi' : forms.Textarea(attrs={'class': 'form-control form-group row' , 'placeholder' : 'Gender'}),
        }

homepage/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['name','fill']
        widgets = {
            'name':forms.TextInput(attrs={'placeholder':'Masukkan nama anda'}),
            'fill':forms.TextInput(attrs={'placeholder':'Masukkan kritik dan saran anda'}),
            }
        labels = { 
            'name':'Nama',
            'fill':'Kritik dan saran',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

subscriber/forms.py
from django import forms
from .models import Subscriber

class SubscriberForm(forms.ModelForm):

    name = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "placeholder" : "Name",
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "placeholder" : "Email",
    }))

    class Meta:
        model = Subscriber
        fields = ['name', 'email']

Barang/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect,HttpResponse
from Barang.forms import BarangForm
from Barang.models import BarangModel


def createBarang(request):
    if request.method == "POST":
        forms= BarangForm(request.POST,request.FILES)
        if forms.is_valid():
            saved = forms.save()
            return redirect("/barang/")
            
    return render(request, "Barang/buatbarang.html", { "data": BarangForm() ,} )

def homepage(request):
    barang_all = BarangModel.objects.filter(terbeli=False)
    return render(request, "Barang/homepage.html", { "barang": barang_all,} )

deskripsi/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect,HttpResponse
from Barang.forms import BarangForm
from Barang.models import BarangModel
from deskripsi.models import BarangPembeli

def detail_barang(request,slug_barang):    
    barang_detail = BarangModel.objects.get(slug = slug_barang)
    return render(request, 'deskripsi/deskripsi_barang.html',{
        "barang":barang_detail,
 })

def beli_barang(request , slug_barang):
    barangnya_dibeli = BarangModel.objects.get(slug=slug_barang )
    barangnya_dibeli.terbeli = True
    barang_terbeli = BarangPembeli(barang = barangnya_dibeli)
    barang_terbeli.save()
    barangnya_dibeli.save()
    return redirect('/')

def barang_terbeli(request):
    barang_dibeli_pengunjung = BarangModel.objects.filter(terbeli=True)
    print(barang_dibeli_pengunjung)
    return render(request , 'deskripsi/barangterbeli.html' , {"barangkebeli" : barang_dibeli_pengunjung,} )

homepage/views.py
from django.shortcuts import render, redirect
from .models import Review
from . import forms

def review(request):
    reviews = Review.objects.all().order_by('id')
    return render(request, 'input.html', {'reviews': reviews})

def review_create(request):
    reviews = Review.objects.all().order_by('id')
    if request.method == 'POST':
        form = forms.ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:review_create')

    else:
        form = forms.ReviewForm()
    return render(request, 'input.html', {'form': form, 'reviews':reviews})

subscriber/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Subscriber
from . import forms


def subscriber(request):
    subscribers = Subscriber.objects.order_by('id')
    return render(request, 'subscriber.html', {'subscribers': subscribers})

def subscriber_create(request):
        if request.method == 'POST':
            form = forms.SubscriberForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('subscriber:subscriber')

        form = forms.SubscriberForm()
        return render(request, 'koran.html', {'form': form})

templates/Barang/buatbarang.html
{% load static %}
{% include 'base.html' %}



{% block title %}
<title>Create Barang </title>
{% endblock %}

{% block body %}
    <div class="container form-parent" style="padding-top: 1em;">
        <div class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Upload Product</div>
        <form method = "post" class="mb-4 form-style" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in data %}
            <div class="form-group row" style="margin-right: 0; margin-bottom: .1em;">
                <div class="col-sm-10">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-submit btn-lg mt-4 ">SUBMIT</button>
        </form>
    </div>
{% endblock %}

templates/Barang/homepage.html
{% load static %}
{% include 'base.html' %}

{% block title %}

<title>Homepage</title>

{% endblock %}

{% block body %}
<section id='product'>
    <div class="container">
        <img class = 'foto-cewek' src="{% static 'img/pictcewek.webp' %}"  alt="">
        <img src="{% static 'img/banner 1.jpg' %}" style='width: 65em; padding-bottom: 10em;' alt="">
        <!-- <p class="banner-header">get your perfectly imperfect skin</p>
        <p class="banner-desc">SCROLL FOR MORE</p> -->
    </div>
    <div class="display-3 text-center mb-2 p-1 mt-4">Our Product</div>
    <div class="container mt-2 p-2">
        <div class="row">
            {% for barangnya in barang  %}
            <div class="col-12 col-md-6 col-xl-4 product-parent mt-4 mb-4">
                <img class ="image-product mb-4" src="{{ barangnya.picture.url }}" alt="">
                <p class='brand-barang'> {{ barangnya.brand_barang }} </p>
                <p class="nama-barang"> {{ barangnya.nama_barang }} </p>
                <p class="price-barang"> Rp{{barangnya.harga}} </p>
                <form action="{% url 'barangdetail' barangnya.slug  %}" enctype="multipart/form-data">
                    <div class="col-12">     
                        <button type="submit" class="btn btn-submit btn-lg mt-4 ">BUY</button>
                    </div> 
                </form>
            </div>
            {% endfor %}
        </div> 
    </div>
</section>
{% endblock %}
        

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">        
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
    <link rel="stylesheet" href="{% static 'css/buatbarang.css' %}">
    <link rel="stylesheet" href="{% static 'css/input.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sanchez&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Tenor+Sans&display=swap" rel="stylesheet">
    {% block title %}


    {% endblock %}
</head>

<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top">
                <a href="#" class="navbar-brand">
                    <img src="https://i.ibb.co/y0QH6Dw/Group-1.jpg" width="234px" height="52px" alt="">
                </a>
                <button class="navbar-toggler navbar-light bg-light" data-toggle="collapse" data-target="#navbarMenu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarMenu">
                    <ul class="navbar-nav mr-auto ml-auto">
                        <li class="nav-item">
                            <a href="{% url 'barang:homepage' %}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'barang:homepage' %}"  class="nav-link">Products</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Pick for Me</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">About</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'barang:createbarang' %}" class="nav-link">Create Barang</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'homepage:review_create' %}" class="nav-link">Review</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'subscriber:subscriber' %}" class="nav-link">Subscriber</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <img src="https://i.ibb.co/yPYKM8Q/account-1.jpg" width="36px" height="38px" alt="">
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'barangterbeli' %}" class="nav-link">
                                <img src="https://i.ibb.co/xFz9HJS/cart-1.jpg" width="50px" height="46px" alt="">
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <img src="https://i.ibb.co/Pwn3KYm/search-1.jpg" width="38px" height="38px" alt="">
                            </a>
                        </li>
                    </ul>
                </div>
        
            </nav>
            {% block body %}
            
            {% endblock %} 
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
                crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
                crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
                crossorigin="anonymous"></script>
  
</body>

</html>

templates/deskripsi/barangterbeli.html
{% load static %}

{% include 'base.html' %}

{% block body %}


<div class="container">
    <h1>Barang Terbeli</h1>
    <div class="row">
        {% for barang in barangkebeli  %}
        <div class="col-md-6">
            <img src="{{ barang.picture.url }}" alt="" class='image-product'>
        </div>
        <div class="col-md-6">
           <p class="brand-barang"> {{ barang.brand_barang }} </p>
            <p class='nama-barang'> {{ barang.nama_barang }} </p>
            <p class="price-barang"> Rp {{ barang.harga }} </p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/deskripsi/deskripsi_barang.html
{% load static %}

{% include 'base.html' %}

{% block body %}
<div class="container">
    <h1>Barang Terbeli </h1>
    <div class="row">
        <div class="col-md-6">
            <img src="{{ barang.picture.url }}" alt="" class='image-product'>
        </div>
        <div class="col-md-6">
            <p class="brand-barang"> {{ barang.brand_barang }} </p>
            <p class='nama-barang'> {{ barang.nama_barang }} </p>
            <p class="price-barang"> Rp {{ barang.harga }} </p>
            <form action="{% url 'barangbeli' barang.slug  %}" enctype="multipart/form-data">   
                <button type="submit" class="btn btn-submit btn-lg mt-4 ">BUY NOW </button> 
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/input.html
{% extends "base.html" %}
    {% block title %}
        <title>Tell Us Your Thoughts!</title>
    {% endblock %}
{% block body %}
<div class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Tell Us Your Thoughts!</div>
<div class="container" style="width: 900px;">
    <div class="row">
        
        {% for review in reviews %}
            <div class="card mb-1" style="width: 282px; font-family: 'Playfair Display'; margin-left: 3px; margin-right: 3px;">
                <div class="card-body">
                <h5 class="card-title">{{ review.name }}'s</h5>
                <h6 class="card-subtitle mb-2 text-muted">testimoni</h6>
                <p class="card-text">{{ review.fill }}</p>
                </div>
            </div> 
        {% endfor %}
    </div>
</div>
    <br>
    <br>
    <br>
    <div class="h2 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Submit Your Responses!</div>
    <form class="css" action="{% url 'homepage:review_create' %}" method="post" style="font-family: 'Playfair Display'">
        {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-2"></div>
                    <div class="form-group col-lg-8 tag">
                        
                        {% for fields in form %}
                            <br>
                            {{ fields.label_tag }} 
                            {{ fields }}
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-2"></div>
                <br>
            <div class="form-row">
                <input type="submit" class="btn mr-auto ml-auto" value="Submit!" style="background-color:#B09586; color: white;">
            </div>
    </form>
    <br>
    <br>
    <br>
{% endblock %}

templates/koran.html
{% load static %}
{% include "base.html" %}

{% block body %}

{% block title %}
<title>Keep in Touch with Us!</title>
{% endblock %}

<form class="css" action="{% url 'subscriber:subscriber_create' %}" method="post">
        <div class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Keep in Touch with Us!</div>
    {% csrf_token %}
    <div class="form-row">
        <div class="col-sm-3"></div>
        <div class="form-group col-sm-6">
            {% for fields in form %}
                <br>
                {{ fields.label_tag }}
                <br>
                {{ fields }}
            {% endfor %}
        </div>
        <div class="col-sm-3"></div>

    </div>
    <div class="form-row">
        <!-- <div class="col-sm-3"></div> -->
        <div class="text-center col-sm-5">
        <input type="submit" class="btn mx-auto my-auto btn-submit:hover btn-submit float-right text" value="Subscribe">
    </div>
    </form>
{% endblock %}

templates/subscriber.html
{% load static %}
{% include "base.html" %}

{% block body %}

{% block title %}
<title>Keep in Touch with Us!</title>
{% endblock %}

      <div class="display-4 p-3 mb-4 text-center" style="font-family: 'Playfair Display';">Subscriber</div>
      <div class="article">
          <a href="{% url 'subscriber:subscriber' %}"></a>
          <div class="article">
              <div class="row">
                  {% for subscriber in subscribers %}
                      <div class="col-sm-3 text-center" style= "font-family: 'Playfair Display';">
                          <h2>{{ subscriber.name }}</h2>
                      </div>
                  {% endfor %}
              </div>
          </div>
      </div>
          <br>
            <div class = 'form-group text-center col-md-9'>
                <a href="{% url 'subscriber:subscriber_create' %}"><button type="button" class= "btn btn-secondary btn-submit btn-submit:hover btn-lg btn-sm">Subscribe Here!</button></a>      
      </div>
  </div>

  
  {% endblock %}
  